name: Decompresser le ZIP

on:
  push:
    branches: [ main, master ]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Telecharger le depot
        uses: actions/checkout@v4

      - name: Decompresser l archive
        run: |
          unzip MbiaDataFlow.zip -d extracted_files

      - name: Sauvegarder les fichiers dans le depot
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add extracted_files/
          git commit -m "Ajout des fichiers decompressés" || echo "Pas de changement a commiter"
          git push
          
